### ISSUE TITLE
Order of lists and list items

### ISSUE THREAD

**Issue by jsnoble7** [jahdaic/WunderPebble#1]
Am loving this app! It's brilliantly designed and works well. Great job.

I've noticed though that the order of both the lists and list items seems to be only in creation order, and it doesn't seem to follow any reordering of items that is done on any other Wunderlist app (or the website). Is this something that could possibly be updated in future releases?

(Sorry, just offering this as a suggestion/feedback as I'm not much of an app builder!)

Thanks.

**Comment by jahdaic** [comment]
I'm currently working on this and hope to release it soon. Since I'm not working with an official API, it's harder to make little details like that work right.

**Comment by Hipska** [comment]
Is there any reason why you just don't use the official API?

**Comment by jahdaic** [comment]
The official API is still in beta. Luckily I just got accepted into the beta and have released a new version of WunderPebble into the Pebble app store. It now sorts tasks and lists in the correct order. I'll update Github soon after cleaning up the code a bit.

**Comment by ploebb** [comment]
Is this feature implemented for lists yet? My tasks are in the correct order - my lists however, are not.
