### ISSUE TITLE
UTF-8 characters not correctly displayed on watch

### ISSUE THREAD

**Issue by Hipska** [jahdaic/WunderPebble#3]
I have a list called 'Privé' and it is displayed as 'PrivÃ©'. Same for an item called 'Rösti' which is displayed as 'RÃ¶sti'.

**Comment by jahdaic** [comment]
I'm looking into this.

**Comment by Hipska** [comment]
I want to help too, but the source seems not to be updated..

**Comment by jahdaic** [comment]
I'm still cleaning it up after the rewrite. I'll try to have it up to date later today.

**Comment by jahdaic** [comment]
May be because only limited characters from the font actually get loaded into the app.

**Comment by jahdaic** [comment]
I think I've tracked down a way to fix it and it's due to the UTF-8 encoding being incorrectly interpreted as ASCII. Hope to have it implemented by the next update if Pebble.js doesn't implement a fix first.

**Comment by Hipska** [comment]
Sounds great, let me know when we can test.

**Comment by Hipska** [comment]
Hey, I recently got a notification from Pebble that the WunderPebble app was updated, but this bug still appears..

**Comment by jahdaic** [comment]
That's strange. I haven't pushed a new update in a while. The last version was 1.2 with support for Wunderlist Folders and new icons.

**Comment by jahdaic** [comment]
This should be solved with version 2.0 of WunderPebble
